[build]
  command = "npm run build"
  publish = "dist"

# Ensure SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Reduce caching so mobile users see updates immediately
# HTML should never be cached aggressively
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Let hashed assets cache long, they are content-addressed by Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
